(() => {
  const STORAGE_KEY = 'promotional-language';
  const translations = {
    id: {
      nav: ['Fitur', 'Cara kerja', 'Privasi', 'Mulai percakapan'],
      home: {
        '.hero .eyebrow': 'Local-first digital signage', '.hero h1': 'Konten Anda. <em>Layar Anda.</em>', '.hero .lead': 'Tampilkan Reels, video, foto, dan carousel dari Instagram Professional Account pada layar digital yang selalu siap menarik perhatian.', '.actions .button': 'Mulai percakapan <span aria-hidden="true">↗</span>', '.actions .text-link': 'Lihat cara kerja <span aria-hidden="true">↓</span>', '.showcase .eyebrow': 'Dibuat untuk display', '.showcase h2': 'Instagram Anda,<br><em>tampil lebih besar.</em>', '.showcase-copy p': 'Konten yang sudah Anda punya, disusun menjadi pengalaman visual yang rapi untuk toko, studio, kantor, lobby, atau event.', '.showcase-copy .text-link': 'Lihat kemampuan produk <span aria-hidden="true">↘</span>', '.feature-intro .eyebrow': 'Yang penting, terlihat jelas', '#features-title': 'Sumber resmi.<br>Playlist rapi.<br><em>Local-first.</em>', '.feature-main h3': 'Instagram Graph API', '.feature-main p': 'Media dimuat melalui sumber resmi dari Instagram Professional Account yang terhubung—bukan dengan scraping.', '.feature-main .card-note': 'OFFICIAL SOURCE', '.feature-playlist h3': 'Playlist yang fleksibel', '.feature-playlist p': 'Pilih media, susun urutan, lalu jalankan playback fullscreen pada display terpisah.', '.feature-local h3': 'Local-first', '.feature-local p': 'Access token tetap di backend lokal dan disimpan terenkripsi. Browser tidak menerimanya.', '.workflow-head .eyebrow': 'Cara kerja', '#workflow-title': 'Hubungkan. Pilih. Putar.', '.workflow-head p': 'Dari akun yang terhubung sampai layar fullscreen, alurnya tetap sederhana.', '.step:nth-child(1) h3': 'Hubungkan', '.step:nth-child(1) p': 'Instagram Professional Account', '.step:nth-child(2) h3': 'Pilih', '.step:nth-child(2) p': 'Pilih dan susun media', '.step:nth-child(3) h3': 'Putar', '.step:nth-child(3) p': 'Jalankan fullscreen display', '.use-cases .eyebrow': 'Satu alur, banyak suasana', '#use-title': 'Layar yang mengikuti<br><em>ruang Anda.</em>', '.security-copy .eyebrow': 'Privasi by design', '#security-title': 'Konten bergerak.<br><em>Token tetap aman.</em>', '.security-copy p': 'Access token tidak dikirim ke browser. Arsitektur local-first menjaga credential tetap berada di backend lokal dan tersimpan dalam bentuk terenkripsi.', '.final-cta .eyebrow': 'Siap ditampilkan', '#cta-title': 'Mari buat layar Anda<br><em>lebih hidup.</em>', '.final-cta p': 'Untuk dukungan dan pertanyaan produk, mulai percakapan dengan kami melalui WhatsApp.', '.final-cta .button': 'Mulai percakapan <span aria-hidden="true">↗</span>'
      },
      useCases: ['Toko', 'Studio', 'Kantor', 'Lobby', 'Event'], footer: ['Privacy', 'Terms', 'Data Deletion'], toggle: 'Beralih ke Bahasa Inggris'
    },
    en: {
      nav: ['Features', 'How it works', 'Privacy', 'Start a conversation'],
      home: {
        '.hero .eyebrow': 'Local-first digital signage', '.hero h1': 'Your content. <em>Your screen.</em>', '.hero .lead': 'Display Reels, videos, photos, and carousels from your Instagram Professional Account on a digital screen that is always ready to attract attention.', '.actions .button': 'Start a conversation <span aria-hidden="true">↗</span>', '.actions .text-link': 'See how it works <span aria-hidden="true">↓</span>', '.showcase .eyebrow': 'Made for display', '.showcase h2': 'Your Instagram,<br><em>bigger.</em>', '.showcase-copy p': 'The content you already have, arranged into a polished visual experience for stores, studios, offices, lobbies, or events.', '.showcase-copy .text-link': 'See product capabilities <span aria-hidden="true">↘</span>', '.feature-intro .eyebrow': 'What matters, clearly visible', '#features-title': 'Official source.<br>Neat playlists.<br><em>Local-first.</em>', '.feature-main h3': 'Instagram Graph API', '.feature-main p': 'Media is loaded through the official source from a connected Instagram Professional Account—not through scraping.', '.feature-main .card-note': 'OFFICIAL SOURCE', '.feature-playlist h3': 'Flexible playlists', '.feature-playlist p': 'Choose media, arrange the order, then run fullscreen playback on a separate display.', '.feature-local h3': 'Local-first', '.feature-local p': 'The access token stays in the local backend and is stored encrypted. The browser never receives it.', '.workflow-head .eyebrow': 'How it works', '#workflow-title': 'Connect. Choose. Play.', '.workflow-head p': 'From the connected account to the fullscreen display, the flow stays simple.', '.step:nth-child(1) h3': 'Connect', '.step:nth-child(1) p': 'Instagram Professional Account', '.step:nth-child(2) h3': 'Choose', '.step:nth-child(2) p': 'Choose and arrange media', '.step:nth-child(3) h3': 'Play', '.step:nth-child(3) p': 'Run fullscreen display', '.use-cases .eyebrow': 'One flow, many settings', '#use-title': 'A screen that follows<br><em>your space.</em>', '.security-copy .eyebrow': 'Privacy by design', '#security-title': 'Content moves.<br><em>Tokens stay safe.</em>', '.security-copy p': 'Access tokens are never sent to the browser. The local-first architecture keeps credentials in the local backend in encrypted form.', '.final-cta .eyebrow': 'Ready to display', '#cta-title': 'Let’s make your screen<br><em>more alive.</em>', '.final-cta p': 'For product support and questions, start a conversation with us through WhatsApp.', '.final-cta .button': 'Start a conversation <span aria-hidden="true">↗</span>'
      },
      useCases: ['Store', 'Studio', 'Office', 'Lobby', 'Event'], footer: ['Privacy', 'Terms', 'Data Deletion'], toggle: 'Switch to Indonesian'
    }
  };
  const privacyTranslations = {
    id: { nav:['Beranda','Ketentuan','Hapus data'], eyebrow:'Dokumen legal', title:'Kebijakan Privasi', updated:'Berlaku mulai: 5 Oktober 2026 · Terakhir diperbarui: 5 Oktober 2026', headings:['1. Tentang layanan','2. Data yang kami proses','3. Cara penggunaan data','4. Penyimpanan dan keamanan','5. Berbagi data','6. Retensi dan hak Anda','7. Perubahan dan kontak'], paragraphs:['Reels Player (“Layanan”) adalah aplikasi digital signage local-first yang membantu operator menampilkan media dari Instagram Professional Account pada layar digital. Layanan ini dioperasikan oleh <strong>CV. Kolaborasi Riggedbox Hompimpa (Rigged Box Softworks)</strong> (“kami”), beralamat di <strong>Jl. Derkuku No. 9, Manahan, Kec. Banjarsari, Surakarta City, Central Java 57139, Indonesia</strong>.','Kami tidak meminta kata sandi Instagram. Jangan kirim data sensitif yang tidak diperlukan.','Data digunakan untuk menghubungkan akun, memvalidasi akses, mengambil media yang diminta, menampilkan playlist, menjaga keamanan aplikasi, memberikan dukungan, dan memenuhi kewajiban hukum. Kami tidak menjual data pribadi, tidak menggunakan data Instagram untuk iklan, dan tidak menggunakan data untuk membangun profil pengguna.','Dalam konfigurasi local-first saat ini, kredensial disimpan oleh backend lokal dalam file terenkripsi. Browser tidak menerima access token privat. Media dan konfigurasi dapat tersimpan pada perangkat tempat aplikasi dijalankan. Anda bertanggung jawab mengamankan perangkat, jaringan, backup, dan akses operator.','Layanan berkomunikasi dengan layanan resmi Meta/Instagram untuk mengambil data yang diminta. Kami tidak membagikan data kepada pihak lain kecuali penyedia infrastruktur yang diperlukan oleh implementasi Anda, atas kewajiban hukum, atau untuk melindungi keamanan dan hak kami. Kami tidak mengklaim kepemilikan atas konten Instagram Anda.','Data disimpan selama diperlukan untuk fungsi aplikasi atau sampai Anda menghapusnya. Anda dapat memutus koneksi akun, menghapus kredensial lokal, meminta salinan/koreksi, atau meminta penghapusan data dengan mengikuti <a href="data-deletion-instructions.html">instruksi penghapusan data</a>.','Kami dapat memperbarui kebijakan ini dan akan menampilkan tanggal terbaru di atas. Pertanyaan privasi dapat dikirim ke <a href="mailto:riggedboxsoftworks.studio@gmail.com">riggedboxsoftworks.studio@gmail.com</a>.'], items:['Access token Instagram yang dimasukkan operator untuk menghubungkan akun profesional.','Informasi akun dan metadata media yang tersedia melalui Instagram Graph API, seperti ID akun, caption, permalink, tipe media, thumbnail, dan URL media sesuai izin yang diberikan.','Konfigurasi playlist, preferensi playback, dan catatan teknis yang diperlukan untuk menjalankan aplikasi.','Data komunikasi yang Anda kirim saat menghubungi kami, seperti nama, email, dan isi pesan.'] },
    en: { nav:['Home','Terms','Delete data'], eyebrow:'Legal document', title:'Privacy Policy', updated:'Effective: October 5, 2026 · Last updated: October 5, 2026', headings:['1. About the service','2. Data we process','3. How we use data','4. Storage and security','5. Data sharing','6. Retention and your rights','7. Changes and contact'], paragraphs:['Reels Player (the “Service”) is a local-first digital signage application that helps operators display media from an Instagram Professional Account on a digital screen. The Service is operated by <strong>CV. Kolaborasi Riggedbox Hompimpa (Rigged Box Softworks)</strong> (“we”), located at <strong>Jl. Derkuku No. 9, Manahan, Kec. Banjarsari, Surakarta City, Central Java 57139, Indonesia</strong>.','We do not ask for your Instagram password. Do not send unnecessary sensitive data.','Data is used to connect accounts, validate access, retrieve requested media, display playlists, secure the application, provide support, and meet legal obligations. We do not sell personal data, use Instagram data for advertising, or build user profiles.','In the current local-first configuration, credentials are stored by the local backend in an encrypted file. The browser does not receive private access tokens. Media and configuration may be stored on the device where the application runs. You are responsible for securing the device, network, backups, and operator access.','The Service communicates with official Meta/Instagram services to retrieve requested data. We do not share data except with required infrastructure providers, when legally required, or to protect our security and rights. We do not claim ownership of your Instagram content.','Data is stored as long as needed or until you delete it. You may disconnect an account, delete local credentials, request a copy or correction, or request deletion by following the <a href="data-deletion-instructions.html">data deletion instructions</a>.','We may update this policy and display the latest date above. Privacy questions may be sent to <a href="mailto:riggedboxsoftworks.studio@gmail.com">riggedboxsoftworks.studio@gmail.com</a>.'], items:['The Instagram access token entered by the operator to connect a professional account.','Account information and media metadata available through the Instagram Graph API, such as account ID, caption, permalink, media type, thumbnail, and media URL according to granted permissions.','Playlist configuration, playback preferences, and technical logs needed to run the application.','Communication data you send when contacting us, such as your name, email, and message.'] }
  };
  function applyPrivacy(language) { const t=privacyTranslations[language]; document.querySelectorAll('.navlinks a').forEach((n,i)=>{if(t.nav[i])n.textContent=t.nav[i]}); document.querySelector('.legal .eyebrow').textContent=t.eyebrow; document.querySelector('.legal h1').textContent=t.title; document.querySelector('.legal .updated').textContent=t.updated; document.querySelectorAll('.legal h2').forEach((n,i)=>n.textContent=t.headings[i]); document.querySelectorAll('.legal p:not(.updated)').forEach((n,i)=>n.innerHTML=t.paragraphs[i]); document.querySelectorAll('.legal li').forEach((n,i)=>n.innerHTML=t.items[i]); document.title=`${t.title} | Reels Player`; }  function apply(language, button) {
    const t = translations[language];
    document.documentElement.lang = language;
    if (document.querySelector(".legal")) applyPrivacy(language); else Object.entries(t.home).forEach(([selector, value]) => document.querySelectorAll(selector).forEach(node => { node.innerHTML = value; }));
    document.querySelectorAll('.navlinks a').forEach((node, i) => { if (t.nav[i]) node.textContent = t.nav[i]; });
    document.querySelectorAll('.use-list span').forEach((node, i) => { if (t.useCases[i]) node.textContent = t.useCases[i]; });
    document.querySelectorAll('.footer nav a').forEach((node, i) => { if (t.footer[i]) node.textContent = t.footer[i]; });
    if (language === 'en') { document.title = 'Instagram Digital Signage | Reels Player — Riggedbox'; document.querySelector('meta[name="description"]')?.setAttribute('content', 'Turn Instagram Professional Account content into digital signage for stores, studios, offices, lobbies, and events.'); }
    else { document.title = 'Digital Signage Instagram | Reels Player — Riggedbox'; document.querySelector('meta[name="description"]')?.setAttribute('content', 'Ubah konten Instagram Professional Account menjadi digital signage yang siap tampil di toko, studio, kantor, lobby, dan event.'); }
    button.textContent = language === 'id' ? 'EN' : 'ID'; button.title = t.toggle; button.setAttribute('aria-label', t.toggle);
    localStorage.setItem(STORAGE_KEY, language);
  }
  document.addEventListener('DOMContentLoaded', () => {
    const nav = document.querySelector('.navlinks'); if (!nav || !document.querySelector('main')) return;
    const button = document.createElement('button'); button.className = 'language-toggle'; button.type = 'button'; nav.prepend(button);
    let language = localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'id'; apply(language, button);
    button.addEventListener('click', () => { language = language === 'id' ? 'en' : 'id'; apply(language, button); });
  });
})();

