(() => {
  const STORAGE_KEY = 'promotional-language';
  const translations = {
    id: {
      nav: ['Fitur', 'Cara kerja', 'Privasi', 'Mulai percakapan'],
      home: {
        '.hero .eyebrow': 'Local-first digital signage', '.hero h1': 'Konten Anda. <em>Layar Anda.</em>', '.hero .lead': 'Tampilkan Reels, video, foto, dan carousel dari Instagram Professional Account pada layar digital yang selalu siap menarik perhatian.', '.actions .button': 'Mulai percakapan <span aria-hidden="true">↗</span>', '.actions .text-link': 'Lihat cara kerja <span aria-hidden="true">↓</span>', '.showcase .eyebrow': 'Dibuat untuk display', '.showcase h2': 'Instagram Anda,<br><em>tampil lebih besar.</em>', '.showcase-copy p': 'Konten yang sudah Anda punya, disusun menjadi pengalaman visual yang rapi untuk toko, studio, kantor, lobby, atau event.', '.showcase-copy .text-link': 'Lihat kemampuan produk <span aria-hidden="true">↘</span>', '.feature-intro .eyebrow': 'Yang penting, terlihat jelas', '#features-title': 'Sumber resmi.<br>Playlist rapi.<br><em>Local-first.</em>', '.feature-main h3': 'Instagram Graph API', '.feature-main p': 'Media dimuat melalui sumber resmi dari Instagram Professional Account yang terhubung—bukan dengan scraping.', '.feature-main .card-note': 'OFFICIAL SOURCE', '.feature-playlist h3': 'Playlist yang fleksibel', '.feature-playlist p': 'Pilih media, susun urutan, lalu jalankan playback fullscreen pada display terpisah.', '.feature-local h3': 'Local-first', '.feature-local p': 'Access token tetap di backend lokal dan disimpan terenkripsi. Browser tidak menerimanya.', '.workflow-head .eyebrow': 'Cara kerja', '#workflow-title': 'Hubungkan. Pilih. Putar.', '.workflow-head p': 'Dari akun yang terhubung sampai layar fullscreen, alurnya tetap sederhana.', '.step:nth-child(1) h3': 'Hubungkan', '.step:nth-child(1) p': 'Instagram Professional Account', '.step:nth-child(2) h3': 'Pilih', '.step:nth-child(2) p': 'Pilih dan susun media', '.step:nth-child(3) h3': 'Putar', '.step:nth-child(3) p': 'Jalankan fullscreen display', '.use-cases .eyebrow': 'Satu alur, banyak suasana', '#use-title': 'Layar yang mengikuti<br><em>ruang Anda.</em>', '.security-copy .eyebrow': 'Privasi by design', '#security-title': 'Konten bergerak.<br><em>Token tetap aman.</em>', '.security-copy p': 'Access token tidak dikirim ke browser. Arsitektur local-first menjaga credential tetap berada di backend lokal dan tersimpan dalam bentuk terenkripsi.', '.final-cta .eyebrow': 'Siap ditampilkan', '#cta-title': 'Mari buat layar Anda<br><em>lebih hidup.</em>', '.final-cta p': 'Untuk dukungan dan pertanyaan produk, mulai percakapan dengan kami melalui WhatsApp.', '.final-cta .button': 'Mulai percakapan <span aria-hidden="true">↗</span>'
      },
      useCases: ['Toko', 'Studio', 'Kantor', 'Lobby', 'Event'], footer: ['Privacy', 'Terms', 'Data Deletion'], toggle: 'Beralih ke Bahasa Inggris'
    },
    en: {
      nav: ['Features', 'How it works', 'Privacy', 'Start a conversation'],
      home: {
        '.hero .eyebrow': 'Local-first digital signage', '.hero h1': 'Your content. <em>Your screen.</em>', '.hero .lead': 'Display Reels, videos, photos, and carousels from your Instagram Professional Account on a digital screen that is always ready to attract attention.', '.actions .button': 'Start a conversation <span aria-hidden="true">↗</span>', '.actions .text-link': 'See how it works <span aria-hidden="true">↓</span>', '.showcase .eyebrow': 'Made for display', '.showcase h2': 'Your Instagram,<br><em>bigger.</em>', '.showcase-copy p': 'The content you already have, arranged into a polished visual experience for stores, studios, offices, lobbies, or events.', '.showcase-copy .text-link': 'See product capabilities <span aria-hidden="true">↘</span>', '.feature-intro .eyebrow': 'What matters, clearly visible', '#features-title': 'Official source.<br>Neat playlists.<br><em>Local-first.</em>', '.feature-main h3': 'Instagram Graph API', '.feature-main p': 'Media is loaded through the official source from a connected Instagram Professional Account—not through scraping.', '.feature-main .card-note': 'OFFICIAL SOURCE', '.feature-playlist h3': 'Flexible playlists', '.feature-playlist p': 'Choose media, arrange the order, then run fullscreen playback on a separate display.', '.feature-local h3': 'Local-first', '.feature-local p': 'The access token stays in the local backend and is stored encrypted. The browser never receives it.', '.workflow-head .eyebrow': 'How it works', '#workflow-title': 'Connect. Choose. Play.', '.workflow-head p': 'From the connected account to the fullscreen display, the flow stays simple.', '.step:nth-child(1) h3': 'Connect', '.step:nth-child(1) p': 'Instagram Professional Account', '.step:nth-child(2) h3': 'Choose', '.step:nth-child(2) p': 'Choose and arrange media', '.step:nth-child(3) h3': 'Play', '.step:nth-child(3) p': 'Run fullscreen display', '.use-cases .eyebrow': 'One flow, many settings', '#use-title': 'A screen that follows<br><em>your space.</em>', '.security-copy .eyebrow': 'Privacy by design', '#security-title': 'Content moves.<br><em>Tokens stay safe.</em>', '.security-copy p': 'Access tokens are never sent to the browser. The local-first architecture keeps credentials in the local backend in encrypted form.', '.final-cta .eyebrow': 'Ready to display', '#cta-title': 'Let’s make your screen<br><em>more alive.</em>', '.final-cta p': 'For product support and questions, start a conversation with us through WhatsApp.', '.final-cta .button': 'Start a conversation <span aria-hidden="true">↗</span>'
      },
      useCases: ['Store', 'Studio', 'Office', 'Lobby', 'Event'], footer: ['Privacy', 'Terms', 'Data Deletion'], toggle: 'Switch to Indonesian'
    }
  };
  function apply(language, button) {
    const t = translations[language];
    document.documentElement.lang = language;
    Object.entries(t.home).forEach(([selector, value]) => document.querySelectorAll(selector).forEach(node => { node.innerHTML = value; }));
    document.querySelectorAll('.navlinks a').forEach((node, i) => { if (t.nav[i]) node.textContent = t.nav[i]; });
    document.querySelectorAll('.use-list span').forEach((node, i) => { if (t.useCases[i]) node.textContent = t.useCases[i]; });
    document.querySelectorAll('.footer nav a').forEach((node, i) => { if (t.footer[i]) node.textContent = t.footer[i]; });
    if (language === 'en') { document.title = 'Instagram Digital Signage | Reels Player — Riggedbox'; document.querySelector('meta[name="description"]')?.setAttribute('content', 'Turn Instagram Professional Account content into digital signage for stores, studios, offices, lobbies, and events.'); }
    else { document.title = 'Digital Signage Instagram | Reels Player — Riggedbox'; document.querySelector('meta[name="description"]')?.setAttribute('content', 'Ubah konten Instagram Professional Account menjadi digital signage yang siap tampil di toko, studio, kantor, lobby, dan event.'); }
    button.textContent = language === 'id' ? 'EN' : 'ID'; button.title = t.toggle; button.setAttribute('aria-label', t.toggle);
    localStorage.setItem(STORAGE_KEY, language);
  }
  document.addEventListener('DOMContentLoaded', () => {
    const nav = document.querySelector('.navlinks'); if (!nav || !document.querySelector('main')) return;
    const button = document.createElement('button'); button.className = 'language-toggle'; button.type = 'button'; nav.prepend(button);
    let language = localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'id'; apply(language, button);
    button.addEventListener('click', () => { language = language === 'id' ? 'en' : 'id'; apply(language, button); });
  });
})();
